#! /bin/sh
# @@@LICENSE
#
#      Copyright (c) 2009-2012 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# LICENSE@@@
# turn on chroot jails:
jail=off
id=`whoami`

for dir in /usr/palm/services /var/usr/palm/services
do
	if [ -d $dir/$1 ]
	then
		cd $dir/$1
		name=$1.js
		if [ ${#name} -gt 15 ]
		then
			name=`expr $name : ".*\.\([^.]*.js\)"`
			if [ ${#name} -gt 15 ]
			then
				name=`expr $name : ".*\(...............\)"`
			fi
		fi
		if [ -f bootstrap.js ]
		then
			bootstrap=bootstrap.js
		else
			bootstrap=/usr/palm/frameworks/private/javascripts/bootstrap.js
		fi

		# don't try to run in jail if we're already not root:
		if [ $jail == on -a ${id} == root ]; then
			jailcmd="/usr/bin/jailer -t triton -i com.palm.triton -p $dir/$1"
		fi
		exec $jailcmd /usr/bin/js --syslog --stdout --v8-flags="--nolock_codegen_pages" --process-name $name -I /usr/palm/frameworks -I /usr/palm/frameworks/private $bootstrap -- /usr/share/ls2

	fi
done
echo "Failed to launch service '$1' - exiting." 2>&1 | logger
exit 1
